joyent/triton-kubernetes

README.md
docs/detailed.md

update references to new repo

---

ansible/clusterUp.yml
ansible/roles/dockersetup/tasks/main.yml
ansible/roles/k8senvironment/tasks/main.yml
ansible/roles/k8setcd/tasks/main.yml
ansible/roles/k8sha/tasks/main.yml
ansible/roles/mysqldb/tasks/main.yml
ansible/roles/rancherha/tasks/main.yml
ansible/roles/rancherhost/tasks/main.yml
ansible/roles/ranchermaster/tasks/main.yml
setup.sh

*   updated ansible log wording
*   updated K8s orchestration nodes reference names

change wording and update hostnames

---

terraform/create-rancher-env.tf
terraform/modules/azure-rancher-k8s/files/rancher_environment_template_search.sh
terraform/modules/azure-rancher-k8s/main.tf
terraform/modules/azure-rancher-k8s/variables.tf
terraform/modules/triton-rancher-k8s/files/rancher_environment_template_search.sh
terraform/modules/triton-rancher-k8s/main.tf
terraform/modules/triton-rancher-k8s/variables.tf
terraform/modules/triton-rancher/files/setup_rancher.sh.tpl

added k8s plane isolation flag

---

terraform/create-rancher-env.tf
terraform/modules/gcp-rancher-k8s/files/install_rancher_agent.sh.tpl
terraform/modules/gcp-rancher-k8s/files/rancher_environment_template.sh
terraform/modules/gcp-rancher-k8s/main.tf
terraform/modules/gcp-rancher-k8s/outputs.tf
terraform/modules/gcp-rancher-k8s/variables.tf

GCP provider

---

README.md
packer/rancher-agent.yaml
packer/rancher-host.yaml
packer/rancher-server.yaml
template_aws_environment.conf
template_azure_environment.conf
template_clustermanager.conf
template_gcp_environment.conf
template_triton_environment.conf
terraform/modules/aws-rancher-k8s/files/install_rancher_agent.sh.tpl
terraform/modules/aws-rancher-k8s/variables.tf
terraform/modules/azure-rancher-k8s/files/install_rancher_agent.sh.tpl
terraform/modules/azure-rancher-k8s/variables.tf
terraform/modules/gcp-rancher-k8s/files/install_rancher_agent.sh.tpl
terraform/modules/gcp-rancher-k8s/variables.tf
terraform/modules/rancher-k8s/variables.tf
terraform/modules/triton-rancher-k8s/files/install_rancher_agent.sh.tpl
terraform/modules/triton-rancher-k8s/variables.tf
terraform/modules/triton-rancher/variables.tf
triton-kubernetes.sh

-   Kubernetes 1.7.7 -> 1.8.5
-   Docker 1.12 -> 17.03-ce

kubernetes upgrade

---

terraform/modules/aws-rancher-k8s/files/install_rancher_agent.sh.tpl
terraform/modules/azure-rancher-k8s/files/install_rancher_agent.sh.tpl
terraform/modules/gcp-rancher-k8s/files/install_rancher_agent.sh.tpl
terraform/modules/triton-rancher-k8s/files/install_rancher_agent.sh.tpl
terraform/modules/triton-rancher/files/install_rancher_master.sh.tpl
triton-kubernetes.sh

-   jq/terraform setup
-   overlay2 docker storage driver - resolves #28

Docker setup

---

cmd/get.go
create/cluster.go
create/cluster_aws.go
create/cluster_azure.go
create/cluster_gcp.go
create/cluster_triton.go
create/manager_triton.go
create/node.go
create/node_test.go
create/node_triton.go
destroy/cluster.go
destroy/node.go
get/cluster.go

- Prompt for node creation after cluster creation
- Prompt for mysql image and package when deploying cluster manager in HA mode
@fayazg 
Note: Since we don't have a `--silent` flag yet we will always prompt for node creation after cluster creation.

More UX Enhancements

---

create/manager_triton.go

Ask for private registry during manager create

---

create/manager_triton.go

Prompt for rancher server/agent image

---

create/manager_triton.go
create/node_triton.go

Remove Triton Package and Image Filters

---

README.md
cmd/destroy.go
cmd/root.go
create/manager_triton.go

Update README, fix config parameter

---

packer/rancher-agent.yaml
packer/rancher-server.yaml
scripts/docker/17.03.sh
terraform/create-rancher.tf
terraform/modules/aws-rancher-k8s-host/files/install_rancher_agent.sh.tpl
terraform/modules/aws-rancher-k8s-host/variables.tf
terraform/modules/azure-rancher-k8s-host/files/install_rancher_agent.sh.tpl
terraform/modules/azure-rancher-k8s-host/variables.tf
terraform/modules/gcp-rancher-k8s-host/files/install_rancher_agent.sh.tpl
terraform/modules/gcp-rancher-k8s-host/variables.tf
terraform/modules/triton-rancher-k8s-host/files/install_rancher_agent.sh.tpl
terraform/modules/triton-rancher-k8s-host/variables.tf

- docker storage driver changes

fix docker configuration

---

create/cluster.go
create/node.go
terraform/modules/aws-rancher-k8s-host/main.tf
terraform/modules/aws-rancher-k8s/files/rancher_environment_template.sh
terraform/modules/aws-rancher-k8s/main.tf
terraform/modules/azure-rancher-k8s/files/rancher_environment_template.sh
terraform/modules/azure-rancher-k8s/main.tf
terraform/modules/gcp-rancher-k8s/files/rancher_environment_template.sh
terraform/modules/gcp-rancher-k8s/main.tf
terraform/modules/triton-rancher-k8s/files/rancher_environment_template.sh
terraform/modules/triton-rancher-k8s/main.tf
terraform/modules/triton-rancher/files/setup_rancher.sh.tpl
terraform/modules/triton-rancher/main.tf
terraform/modules/triton-rancher/outputs.tf
terraform/modules/triton-rancher/variables.tf

Enabled Access Control for Rancher

---

create/cluster.go
create/manager_triton.go
terraform/modules/triton-rancher/files/install_rancher_master.sh.tpl

- Refine user's prompt and relevant options

UX Enhancements

---

Makefile
cmd/root.go
cmd/version.go
cmd/version_test.go
main.go
test_pkg/alter.go
test_pkg/t.go

- Set Version to build
- Add unit tests for Version module

CLI version module

---

examples/apps/guestbook/README.md
examples/apps/ingress/README.md
examples/apps/ingress/ingress.yaml

- ingress example
- php guestbook app from kubernetes/examples

adding ingress example and guestbook app

---

docs/guide/aws/cluster-manager.md
docs/guide/aws/cluster.md
docs/guide/azure/cluster-manager.md
docs/guide/azure/cluster.md
docs/guide/bare-metal/cluster-manager.md
docs/guide/bare-metal/cluster.md
docs/guide/gcp/cluster-manager.md
docs/guide/gcp/cluster.md
docs/guide/gke/cluster.md
docs/guide/triton/cluster-manager.md
docs/guide/triton/cluster.md
docs/guide/vSphere/cluster.md

- gke documentation
- fix formatting

added gke documentation

---

Gopkg.lock
create/cluster_gke.go

pull gke versions from API, fixes #140

---

terraform/modules/files/setup_rancher.sh.tpl

wait for apt-get to finish before running again

---

Makefile
cmd/version.go
cmd/version_test.go

remove the v from version number

---

create/cluster.go
docs/guide/aws/cluster.md
docs/guide/azure/cluster.md
docs/guide/gcp/cluster.md
docs/guide/silent-install-yaml.md
docs/guide/triton/cluster.md
docs/guide/vSphere/cluster.md
examples/silent-install/gcp/cluster-gcp-ha.yaml
examples/silent-install/triton/cluster-triton-ha.yaml
terraform/modules/aws-rancher-k8s-host/variables.tf
terraform/modules/aws-rancher-k8s/variables.tf
terraform/modules/aws-rancher/variables.tf
terraform/modules/azure-rancher-k8s-host/variables.tf
terraform/modules/azure-rancher-k8s/variables.tf
terraform/modules/azure-rancher/variables.tf
terraform/modules/azure-rke/variables.tf
terraform/modules/bare-metal-rancher-k8s-host/variables.tf
terraform/modules/bare-metal-rancher-k8s/variables.tf
terraform/modules/bare-metal-rancher/variables.tf
terraform/modules/gcp-rancher-k8s-host/variables.tf
terraform/modules/gcp-rancher-k8s/variables.tf
terraform/modules/gcp-rancher/variables.tf
terraform/modules/triton-rancher-k8s-host/variables.tf
terraform/modules/triton-rancher-k8s/variables.tf
terraform/modules/triton-rancher/variables.tf
terraform/modules/vsphere-rancher-k8s-host/variables.tf
terraform/modules/vsphere-rancher-k8s/variables.tf

Added support for Kubernetes:
v1.8.11
v1.9.7
v1.10.3
v1.11.8
v1.12.6
**v1.13.4** (New Default)
Also upgraded to Rancher v2.1.7

Upgrade to latest Kubernetes

---

create/cluster.go
docs/guide/aws/cluster.md
docs/guide/azure/cluster.md
docs/guide/gcp/cluster.md
docs/guide/silent-install-yaml.md
docs/guide/triton/cluster.md
docs/guide/vSphere/cluster.md
examples/silent-install/gcp/cluster-gcp-ha.yaml
examples/silent-install/triton/cluster-triton-ha.yaml
terraform/modules/aws-rancher-k8s-host/variables.tf
terraform/modules/aws-rancher-k8s/variables.tf
terraform/modules/aws-rancher/variables.tf
terraform/modules/azure-rancher-k8s-host/variables.tf
terraform/modules/azure-rancher-k8s/variables.tf
terraform/modules/azure-rancher/variables.tf
terraform/modules/azure-rke/variables.tf
terraform/modules/bare-metal-rancher-k8s-host/variables.tf
terraform/modules/bare-metal-rancher-k8s/variables.tf
terraform/modules/bare-metal-rancher/variables.tf
terraform/modules/files/setup_rancher.sh.tpl
terraform/modules/gcp-rancher-k8s-host/variables.tf
terraform/modules/gcp-rancher-k8s/variables.tf
terraform/modules/gcp-rancher/variables.tf
terraform/modules/triton-rancher-k8s-host/variables.tf
terraform/modules/triton-rancher-k8s/variables.tf
terraform/modules/triton-rancher/variables.tf
terraform/modules/vsphere-rancher-k8s-host/variables.tf
terraform/modules/vsphere-rancher-k8s/variables.tf

Added support for Kubernetes:
v1.14.9
v1.15.6
v1.16.3 (New Default)
Also upgraded to Rancher v2.3.3

K8s Upgrade
